function [g,solver_opts] = get_noise_fun()

% g = eye(3);
% g = 0.01*ones(3,1);
B = 0.001*eye(6);
S = [1 0 0 -1 -1 0;0 0 -1 1 0 0;0 1 0 0 0 -1];
g = S*B;

solver_opts = sdeset('SDEType','Ito',...
                 'RandSeed',2,...
                 'ConstGFUN','yes',...
                 'ConstDGFUN','yes',...
                 'NonNegative','yes',...
                 'DiagonalNoise','no'); % default for DiagonalNoise is yes