% Figure 1 E and F - Plot multiple steady states within the boundary generated by
% the stoichiometric model
% build stoichioemtrc matrices
addpath(genpath('C:\Users\shyam\Documents\Courses\CHE1125Project\IntegratedModels\KineticModel'));
rxfname = 'C:\Users\shyam\Documents\Courses\CHE1125Project\IntegratedModels\KineticModel\Kotte2014\Kotte2014.txt';
cnfname = 'C:\Users\shyam\Documents\Courses\CHE1125Project\IntegratedModels\KineticModel\Kotte2014\Kotte2014C.txt';

% create model structure
[FBAmodel,parameter,variable,nrxn,nmetab] = modelgen(rxfname);

% obtain conentrations from file
[mc,FBAmodel,met] = readCNCfromFile(cnfname,FBAmodel);

% run FBA
Vup_struct.ACt2r = 2;
Vup_struct.ENZ1ex = 1;
FBAmodel = FBAfluxes(FBAmodel,'fba',{'ACt2r','ENZ1ex'},Vup_struct,...
                    [find(strcmpi(FBAmodel.rxns,'FDex'))...
                     find(strcmpi(FBAmodel.rxns,'PEPex'))]);
                 
% flux envelope
[hfig,hsubfig,prxnid,flag] = FluxEnvelope(FBAmodel,...
                        {'bmt2r','PEPt2r'},...
                        {'ACt2r','ENZ1ex'});   
                    
% remove metabolites held constant from consideration in the model
% integration phase
[model,pvec,newmc,cnstmet] =...
remove_eMets(FBAmodel,parameter,mc,[FBAmodel.Vind FBAmodel.Vex],...
{'enz1[c]','enz1[e]','enz[e]','ac[e]','bm[c]','bm[e]','pep[e]'});

% only initialize for varmets   
nvar = length(model.mets)-length(find(cnstmet));
M = newmc(1:nvar);
PM = newmc(nvar+1:end);
model.PM = PM;                    
                    
% call to parameter sampling script for analysis of mss
% parameters
clear pvec
kEcat = 1;
KEacetate = 0.1;    % or 0.02
KFbpFBP = 0.1;
vFbpmax = 1;
Lfbp = 4e6;
KFbpPEP = 0.1;
vEXmax = 1;
KEXPEP = 0.3;
vemax = 1.1;        % for bifurcation analysis: 0.7:0.1:1.3
KeFBP = 0.45;       % or 0.45
ne = 2;             % or 2
acetate = 0.1;      % a.u acetate
d = 0.25;           % or 0.25 or 0.35
kPEPout = 0.2;
pvec = [KEacetate,KFbpFBP,Lfbp,KFbpPEP,...
        KEXPEP,vemax,KeFBP,ne,acetate,d,...
        kPEPout,kEcat,vFbpmax,vEXmax];

% systems check
givenModel = @(t,x)KotteODE(t,x,model,pvec);
fluxg = Kotte_givenFlux([M;model.PM],pvec,model);
dMdtg = givenModel(0,M);

tspan = 0:0.1:500;    
npts = 1;
allpvec = pvec;

% run equilibrium solution followed by MATCONT
opts = odeset('RelTol',1e-12,'AbsTol',1e-10);
ac = find(strcmpi(model.mets,'ac[e]'));
allxeq = zeros(length(M),npts);
allxdyn = zeros(length(M),length(tspan),npts);
allxf = zeros(length(M),npts);
allfeq = zeros(length(fluxg),npts);
allfdyn = zeros(length(fluxg),length(tspan),npts);
solveEquilibriumODE     

% extending existing bifurcation diagram for pep and fdp
% take last point of data.x1 as par value and initial val
% integrate until beyond the LP
% jx1 = 1;
% acon = data.x1(4,end)+0.0095*jx1;
% while acon <= data.x1(end,data.s1(2).index)  
%     acon = data.x1(4,end)+0.0095*jx1;
%     pvec(ap) = acon;
%     model.PM(ac-nvar) = acon;
%     ival = data.x1(1:nvar,end);
%     [~,xeq1,~,feq1] = solveODEonly(1,ival,model,pvec,opts,0:0.1:2000);
%     newx1 = [xeq1;pvec(ap)];
%     data.x1 = [data.x1 newx1];
%     data.flux = [data.flux feq1];
%     [~,lambda] = getKotteJacobian(xeq1,pvec,model);
%     data.f1 = [data.f1 lambda];
%     jx1 = jx1+1;
% end
% bifurcationPlot(data.x1,data.s1,data.f1,[4,1]);    
% bifurcationPlot(data.x1,data.s1,data.f1,[4,2]);

% get saddle node
[saddle,saddlepar] = getsaddlenode(data.s1,data.x1,5e-3);
pvec(9) = saddlepar;
model.PM(ac-length(saddle)) = saddlepar;

% perturb saddle to get steady states
eps = 1e-4;
tspanf = 0:0.1:2000;
pival = saddle+eps*[1;1;1];
[~,xeq1,~,feq1] = solveODEonly(1,pival,model,pvec,opts,tspanf);
nival = saddle-eps*[1;1;1];
[~,xeq2,~,feq2] = solveODEonly(1,nival,model,pvec,opts,tspanf);
fss = [feq1 feq2];
% fss(:,1) = fss(:,1)/fss(1,1);
% fss(:,2) = fss(:,2)/fss(1,2);

fid = [3 5];
if isempty(fss)
    % plot initial and final values from continuation only
    plotPointsonFluxEnvelope(hfig,hsubfig,fid,[ifval ffval]);
elseif size(fss,2)>=2
    % plot all the ultiple steady states
    plotPointsonFluxEnvelope(hfig,hsubfig,fid,fss)    
elseif size(fss,2)>=1
    % plot initial , unstabel and final conitunation values
    plotPointsonFluxEnvelope(hfig,hsubfig,fid,[ifval fss ffval]);
end

% plot fss and saddle on bifurcation diagram - figure handle is hbif1 in
% solveEquilibriumODE
habif = get(hbif1,'Children');
set(0,'CurrentFigure',hbif1);
set(hbif1,'CurrentAxes',habif);
colorSpec = chooseColors(2,{'HotPink','Navy'});
plot(saddlepar,saddle(1),'LineStyle','none','Marker','o',...
                                            'MarkerSize',20,...
                                            'MarkerFaceColor',[.2 1 .9],...
                                            'MarkerEdgeColor',[.2 1 .9]);
plot(saddlepar,xeq1(1),'LineStyle','none','Marker','p',...
                                            'MarkerSize',20,...
                                            'MarkerFaceColor',colorSpec{2},...
                                            'MarkerEdgeColor',colorSpec{2});
plot(saddlepar,xeq2(1),'LineStyle','none','Marker','p',...
                                            'MarkerSize',20,...
                                            'MarkerFaceColor',colorSpec{1},...
                                            'MarkerEdgeColor',colorSpec{1});                                        
% FIGmssEqIvalPerturbations(saddle,fss(:,1),2,[1 2],hbif1,habif);

NumericalSeparatrix(model,pvec,opts,ap,data.s1,data.x1,[xeq1 xeq2],5e-3);